import Card from "@/components/card/card";
import React from "react";
import { LaptopList } from "@/feature/laptop-list";
import { AccessoryList } from "@/feature/Accessory-list";

const products = {
  product1: {
    image: "/product1.png",
    title: "Gaming Laptop",
  },
  product2: {
    image: "/product2.png",
    title: "Accessory",
  },
  product3: {
    image: "/product3.png",
    title: "Bags",
  },
  product4: {
    image: "/product4.png",
    title: "Batteries",
  },
  product5: {
    image: "/product5.png",
    title: "Head phone",
  },
  product6: {
    image: "/product6.png",
    title: "Desktop laptop",
  },
};

export const metadata = {
  title: "Products website",
  description: "Generated by Obada.Kahlous",
};

export default function Home() {
  return (
    <div className="sm:container sm:w-full w-[90%] mx-auto my-16 ">
      <div className="my-[10px]">
        <h2 className="text-[34px] text-[#2a2a2a] font-[7000]"> Categories </h2>
        <span className="text-[14px] text-[#a1a1a1] font-[400] ">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, cum!
        </span>
      </div>
      <div className="grid grid-cols-12 gap-4">
        <div className="md:col-span-6 col-span-12">
          <div className="grid grid-cols-12 gap-4">
            <div className="col-span-12">
              <Card
                height="300px"
                rounded="10px"
                width="100%"
                image={products.product1.image}
                title={products.product1.title}
                price={""}
              />
            </div>
            <div className="col-span-12">
              <Card
                height="300px"
                rounded="10px"
                width="100%"
                image={products.product6.image}
                title={products.product6.title}
                price={""}
              />
            </div>
          </div>
        </div>
        <div className="md:col-span-6 col-span-12">
          <div className="grid grid-cols-12 gap-4">
            <div className="md:col-span-6 col-span-12">
              <Card
                height="300px"
                rounded="10px"
                width="100%"
                image={products.product2.image}
                title={products.product2.title}
                price={""}
              />
            </div>
            <div className="md:col-span-6 col-span-12">
              <Card
                height="300px"
                rounded="10px"
                width="100%"
                image={products.product3.image}
                title={products.product3.title}
                price={""}
              />
            </div>
            <div className="md:col-span-6 col-span-12">
              <Card
                height="300px"
                rounded="10px"
                width="100%"
                image={products.product4.image}
                title={products.product4.title}
                price={""}
              />
            </div>
            <div className="md:col-span-6 col-span-12">
              <Card
                height="300px"
                rounded="10px"
                width="100%"
                image={products.product5.image}
                title={products.product5.title}
                price={""}
              />
            </div>
          </div>
        </div>
      </div>

      <LaptopList />
      <AccessoryList />
    </div>
  );
}
