import Card from "@/components/card/card";
import MultipleItems from "@/components/react-slick/react-slick";
import React from "react";

const products = {
  product1: {
    image: "/product1.png",
    title: "Product1",
    price: "1000S.P",
  },
  product2: {
    image: "/product2.png",
    title: "Product2",
    price: "1000S.P",
  },
  product3: {
    image: "/product3.png",
    title: "Product3",
    price: "1000S.P",
  },
  product4: {
    image: "/product4.png",
    title: "Product4",
    price: "1000S.P",
  },
  product5: {
    image: "/product5.png",
    title: "Product5",
    price: "1000S.P",
  },
  product6: {
    image: "/product6.png",
    title: "Product6",
    price: "1000S.P",
  },
};

export const metadata = {
  title: "Products website",
  description: "Generated by Obada.Kahlous",
};

export default function Home() {
  return (
    <div className="sm:container sm:w-full w-[90%] mx-auto my-16 ">
      <div className="grid grid-cols-12 gap-4">
        <div className="md:col-span-6 col-span-12">
          <div className="grid grid-cols-12 gap-4">
            <div className="col-span-12">
              <Card
                height="300px"
                rounded="10px"
                width="100%"
                image={products.product1.image}
                title={products.product1.title}
                price={products.product1.price}
              />
            </div>
            <div className="col-span-12">
              <Card
                height="300px"
                rounded="10px"
                width="100%"
                image={products.product6.image}
                title={products.product6.title}
                price={products.product6.price}
              />
            </div>
          </div>
        </div>
        <div className="md:col-span-6 col-span-12">
          <div className="grid grid-cols-12 gap-4">
            <div className="md:col-span-6 col-span-12">
              <Card
                height="300px"
                rounded="10px"
                width="100%"
                image={products.product2.image}
                title={products.product2.title}
                price={products.product2.price}
              />
            </div>
            <div className="md:col-span-6 col-span-12">
              <Card
                height="300px"
                rounded="10px"
                width="100%"
                image={products.product3.image}
                title={products.product3.title}
                price={products.product3.price}
              />
            </div>
            <div className="md:col-span-6 col-span-12">
              <Card
                height="300px"
                rounded="10px"
                width="100%"
                image={products.product4.image}
                title={products.product4.title}
                price={products.product4.price}
              />
            </div>
            <div className="md:col-span-6 col-span-12">
              <Card
                height="300px"
                rounded="10px"
                width="100%"
                image={products.product5.image}
                title={products.product5.title}
                price={products.product5.price}
              />
            </div>
          </div>
        </div>
      </div>

      <div className="container mx-auto my-[40px]">
        <div className="my-[10px]">
          <h2 className="text-[34px] text-[#2a2a2a] font-[7000]"> Laptop </h2>
          <span className="text-[14px] text-[#a1a1a1] font-[400] ">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, cum!
          </span>
        </div>
        <div className="my-[40px]">
          <MultipleItems />
        </div>
      </div>
    </div>
  );
}
