import { AllProductPage } from "@/feature/all-products-list";

export const metadata = {
  title: "Products page",
  description: "Generated by Obada.Kahlous",
};

export default function Products() {
  return (
    <div className="container mx-auto">
      <AllProductPage />
    </div>
  );
}
